const {designSelect,editorClick,closeDesign}=require('../support/editor.cjs');
const {test,expect}=require('@playwright/test'),{png}=require('../support/color-fixture.cjs');
async function start(page,count=8){
 await page.route('**/face_detection.js',r=>r.fulfill({contentType:'text/javascript',body:'window.FaceDetection=class{setOptions(){}onResults(fn){this.fn=fn}async send(){this.fn({detections:[]})}close(){}}'}));
 await page.goto('/');const picker=page.waitForEvent('filechooser');await page.locator('#photosInput').click();await(await picker).setFiles(Array.from({length:count},(_,i)=>({name:'photo-'+i+'.png',mimeType:'image/png',buffer:png([220-i*10,40,50],[30,150,200])})));
 await expect(page.locator('#journeyCreate')).toBeEnabled();await page.locator('#journeyCreate').click();await expect(page.locator('html')).toHaveAttribute('data-photo-import-phase','idle');
}
test('formats adapt the canvas, PNG, bounded template previews and saved project',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await start(page);await page.locator('#browseCollections').click();await expect(page.locator('#journeyCreate')).toBeEnabled();await page.locator('[data-filter=minimal]').click();expect(await page.locator('.journeyTemplate').count()).toBeGreaterThan(2);
 await page.locator('#journeyFormat').selectOption('9:16');await page.locator('#journeyPreview').click();await expect(page.locator('#journeyLargePreview')).toBeVisible();const preview=await page.locator('#largePreviewPages .journeyPage').first().boundingBox();expect(preview.width/preview.height).toBeCloseTo(9/16,2);await page.locator('#closeLargePreview').click();await page.locator('#journeyCreate').click();
 for(const [format,height] of [['9:16',1920],['1:1',1080],['4:5',1350]]){
  await designSelect(page,'#frameFormat',format);const box=await page.locator('#stage .slide').first().boundingBox();expect(box.width/box.height).toBeCloseTo(1080/height,2);
  const exported=await page.evaluate(async()=>{const file=await renderSlideToFile(0),im=await createImageBitmap(file);const size=[im.width,im.height];im.close();return size});expect(exported).toEqual([1080,height]);
 }
 await designSelect(page,'#frameFormat','9:16');await page.screenshot({path:'test-results/mobile-9-16-'+test.info().project.name+'.png'});await page.reload();await page.locator('#resumeBtn').click();await expect(page.locator('#frameFormat')).toHaveValue('9:16');expect(errors).toEqual([]);
});
test('replace existing and new photos preserves the frame, undo, original files and restore',async({page})=>{
 await start(page);await page.locator('#stage .imgLayer').first().tap();const target=await page.evaluate(()=>({id:S.selected,photo:currentLayer().photo.id,geometry:[currentLayer().x,currentLayer().y,currentLayer().w,currentLayer().h,currentLayer().rot],pages:S.slides.length}));
 await page.locator('#uxReplace').click();await page.locator('#cancelReplacement').click();expect(await page.evaluate(()=>currentLayer().photo.id)).toBe(target.photo);
 await page.locator('#uxReplace').click();await page.locator('#replacementPhotos button:enabled').first().click();expect(await page.evaluate(()=>[currentLayer().x,currentLayer().y,currentLayer().w,currentLayer().h,currentLayer().rot])).toEqual(target.geometry);await editorClick(page,'#undoBtn');expect(await page.evaluate(id=>S.slides.flatMap(s=>s.layers).find(l=>l.id===id).photo.id,target.id)).toBe(target.photo);
 await page.locator('#stage .imgLayer').first().tap();await page.locator('#uxReplace').click();const chooser=page.waitForEvent('filechooser');await page.locator('#replaceFromDevice').click();await(await chooser).setFiles({name:'new.png',mimeType:'image/png',buffer:png([5,230,20],[5,230,20])});await expect(page.locator('html')).toHaveAttribute('data-project-busy','false');await expect(page.locator('#photoReplacement')).not.toBeVisible();
 expect(await page.evaluate(()=>currentLayer().photo.name)).toBe('new.png');expect(await page.evaluate(()=>[currentLayer().x,currentLayer().y,currentLayer().w,currentLayer().h,currentLayer().rot])).toEqual(target.geometry);expect(await page.evaluate(()=>S.photos.length)).toBe(9);
 await editorClick(page,'#undoBtn');expect(await page.evaluate(id=>S.slides.flatMap(s=>s.layers).find(l=>l.id===id).photo.id,target.id)).toBe(target.photo);await editorClick(page,'#redoBtn');await page.reload();await page.locator('#resumeBtn').click();await expect(page.locator('#studioScreen')).toHaveClass(/on/);expect(await page.evaluate(()=>S.slides.flatMap(s=>s.layers).some(l=>l.photo?.name==='new.png'))).toBe(true);expect(await page.evaluate(async()=> (await FramePhotoStore.originals(S.photos)).length)).toBe(9);
});
test('scoped variation conserves other pages and fixed photos; navigation and order have undo',async({page})=>{
 await start(page,12);await designSelect(page,'#templateFamily','collector');await page.locator('#pageJump').selectOption('1');const before=await page.evaluate(()=>({pages:S.slides.map(sl=>JSON.stringify(sl)),ids:S.slides.map(sl=>sl.id),photos:S.slides[1].layers.filter(l=>l.type==='img').map(l=>l.photo.id)}));
 await designSelect(page,'#variationScope','page');await editorClick(page,'#fastNewDesign');await expect(page.locator('html')).toHaveAttribute('data-project-busy','false');const after=await page.evaluate(()=>S.slides);for(const [i,id] of before.ids.entries())if(i!==1)expect(JSON.stringify(after.find(sl=>sl.id===id))).toBe(before.pages[i]);expect(await page.evaluate(()=>S.currentSlide)).toBe(1);
 await page.locator('#pageOrder').click();await page.getByRole('button',{name:'Bajar página 2',exact:true}).click();await page.locator('#closePageOrder').click();expect(await page.evaluate(()=>S.currentSlide)).toBeGreaterThan(1);await editorClick(page,'#undoBtn');expect(await page.evaluate(()=>S.currentSlide)).toBe(1);
 await page.locator('#stage .slide[data-slide="1"] .imgLayer').first().tap();await page.locator('#uxEdit').click();await page.locator('#pePinPhoto').click();const pinned=await page.evaluate(()=>JSON.stringify(S.slides[1]));await editorClick(page,'#fastNewDesign');await expect(page.locator('html')).toHaveAttribute('data-project-busy','false');expect(await page.evaluate(()=>JSON.stringify(S.slides[1]))).toBe(pinned);await expect(page.locator('#toast')).toContainText('Libera');
 const last=await page.locator('#pageJump option').last().getAttribute('value');await page.locator('#pageJump').selectOption(last);expect(await page.locator('#filmstrip .thumb.on').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth})).toBe(true);
});
test('replacement storage failure retains the previous saved project and offers recovery',async({page})=>{
 await start(page,2);const saved=await page.evaluate(()=>localStorage.getItem(SAVE_KEY));await page.evaluate(()=>{FramePhotoStore.put=async()=>{throw Error('quota')}});await page.locator('#stage .imgLayer').first().tap();await page.locator('#uxReplace').click();const chooser=page.waitForEvent('filechooser');await page.locator('#replaceFromDevice').click();await(await chooser).setFiles({name:'unsaved.png',mimeType:'image/png',buffer:png([0,230,0],[0,230,0])});await expect(page.locator('html')).toHaveAttribute('data-project-busy','false');await expect(page.locator('#storageNotice')).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem(SAVE_KEY))).toBe(saved);expect(await page.evaluate(async()=> (await renderSlideToFile(0)).size)).toBeGreaterThan(1000);
});
test('cancelling a replacement during analysis never commits its photo',async({page})=>{
 await start(page,2);const before=await page.evaluate(()=>({saved:localStorage.getItem(SAVE_KEY),pages:JSON.stringify(S.slides),photos:S.photos.length}));
 await page.evaluate(()=>{const analyze=FramePhotoAnalysis.analyzePhotos;FramePhotoAnalysis.analyzePhotos=async(...args)=>{await new Promise(resolve=>window.continueReplacement=resolve);return analyze(...args)}});
 await page.locator('#stage .imgLayer').first().tap();await page.locator('#uxReplace').click();const chooser=page.waitForEvent('filechooser');await page.locator('#replaceFromDevice').click();await(await chooser).setFiles({name:'cancelled.png',mimeType:'image/png',buffer:png([0,230,0],[0,230,0])});await expect(page.locator('html')).toHaveAttribute('data-project-busy','true');await page.locator('#cancelReplacement').click();await page.evaluate(()=>window.continueReplacement());await expect(page.locator('html')).toHaveAttribute('data-project-busy','false');expect(await page.evaluate(()=>JSON.stringify(S.slides))).toBe(before.pages);expect(await page.evaluate(()=>S.photos.length)).toBe(before.photos);expect(await page.evaluate(()=>localStorage.getItem(SAVE_KEY))).toBe(before.saved);
});
test('changing format retains the chosen visual family, hand edits and panorama groups',async({page})=>{
 await start(page);const family=await page.evaluate(()=>S.frameArtDirection);await page.locator('#stage .imgLayer').first().tap();await page.locator('#uxEdit').click();await page.locator('#peContain').click();await page.locator('#peDone').click();const edited=await page.evaluate(()=>({id:currentLayer().id,photo:currentLayer().photo.id,ratio:currentLayer().w/currentLayer().h}));
 await designSelect(page,'#frameFormat','1:1');expect(await page.evaluate(()=>S.frameArtDirection)).toBe(family);expect(await page.evaluate(id=>{const l=S.slides.flatMap(sl=>sl.layers).find(l=>l.id===id);return {photo:l.photo.id,ratio:l.w/l.h,fit:l.fit}},edited.id)).toEqual({photo:edited.photo,ratio:edited.ratio,fit:'contain'});expect(await page.evaluate(()=>S.slides.some(sl=>sl.frameLocked))).toBe(false);
});
