(()=>{
const PREF='frame_speed_prefs_v1';
const css=document.createElement('style');css.textContent=`
.quickbar{display:grid;grid-template-columns:1fr 1.22fr 1fr;gap:8px;padding:0 16px 10px}.quickbar button{min-height:42px;padding:0 12px;border-radius:999px;border:1px solid #292930;background:#121215;font-size:11px;font-weight:750}.quickbar .newDesign{background:#f2f2f4;color:#09090b;border-color:#f2f2f4}.quickbar.busy{pointer-events:none}.quickbar.busy button{opacity:.42}.speedHidden{display:none!important}.fastToastAction{position:fixed;left:50%;bottom:calc(96px + env(safe-area-inset-bottom));transform:translateX(-50%);z-index:110;background:#f4f4f5;color:#09090b;padding:9px 13px;border-radius:999px;font-size:11px;font-weight:750;box-shadow:0 12px 40px rgba(0,0,0,.4);opacity:0;pointer-events:none;transition:.18s}.fastToastAction.on{opacity:1;pointer-events:auto}.studioTop{padding-bottom:5px}.studioTop h1{font-size:31px!important}.emptyQuick{display:none;margin:72px 22px 0;text-align:center}.emptyQuick.on{display:block}.emptyQuick .emptyIcon{width:62px;height:62px;margin:0 auto 18px;border-radius:22px;border:1px solid #292930;display:grid;place-items:center;font-size:27px;background:#111114}.emptyQuick b{display:block;font-size:19px}.emptyQuick small{display:block;color:#73737c;margin:8px auto 20px;max-width:245px;line-height:1.45}.emptyQuick button{min-height:48px;padding:0 22px;border:0;border-radius:999px;background:#f4f4f5;color:#0b0b0d;font-weight:800}.emptyQuick button:disabled{opacity:.55}.emptyStateFast .quickbar,.emptyStateFast #controlBar,.emptyStateFast .canvasWrap,.emptyStateFast .filmstrip,.emptyStateFast .pager,.emptyStateFast .dock{display:none!important}.emptyStateFast .studioTop #modeLabel{display:none}.emptyStateFast .studioTop{border-bottom:0!important}
.frameBriefBackdrop{position:fixed;inset:0;z-index:190;background:rgba(4,4,6,.76);backdrop-filter:blur(12px);display:none;align-items:flex-end;padding:12px 12px calc(12px + env(safe-area-inset-bottom));box-sizing:border-box}.frameBriefBackdrop.on{display:flex}.frameBriefCard{width:100%;max-width:520px;margin:0 auto;background:#121216;border:1px solid #2b2b31;border-radius:27px;padding:19px 16px 15px;box-shadow:0 28px 90px rgba(0,0,0,.58)}.frameBriefEyebrow{font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:#73737d;margin-bottom:6px}.frameBriefCard h3{font-size:20px;line-height:1.15;margin:0 0 7px}.frameBriefIntro{font-size:11px;line-height:1.45;color:#85858e;margin-bottom:16px}.briefQ{margin:13px 0}.briefQ b{display:block;font-size:11px;margin-bottom:8px}.briefChoices{display:grid;grid-template-columns:1fr 1fr;gap:7px}.briefChoices button{min-height:42px;border-radius:14px;border:1px solid #2e2e35;background:#0d0d10;color:#d8d8dd;font-size:11px;font-weight:700;padding:8px 10px}.briefChoices button.on{background:#f1f1f3;color:#0a0a0c;border-color:#f1f1f3}.briefDensity{grid-template-columns:repeat(3,1fr)}.briefActions{display:grid;grid-template-columns:.8fr 1.2fr;gap:8px;margin-top:15px}.briefActions button{min-height:46px;border-radius:999px;border:1px solid #2d2d33;background:#111115;color:#d7d7dc;font-weight:800}.briefActions .primary{background:#f4f4f5;color:#09090b;border-color:#f4f4f5}
`;document.head.appendChild(css);
let prefs={};try{prefs=JSON.parse(localStorage.getItem(PREF)||'{}')}catch(e){}
const studio=$('#studioScreen'),top=studio?.querySelector('.studioTop');
const qb=document.createElement('div');qb.className='quickbar';qb.innerHTML='<button id="fastAdd">＋ Fotos</button><button class="newDesign" id="fastNewDesign">✦ Otra opción</button><button id="fastExport">↑ Exportar</button>';if(top)top.after(qb);
const empty=document.createElement('div');empty.className='emptyQuick';empty.innerHTML='<div class="emptyIcon">▧</div><b>Empieza con tus fotos</b><small>Sube varias imágenes y FRAME arma el primer carrusel automáticamente.</small><button id="emptyAdd">＋ Elegir fotos</button>';if(qb)qb.after(empty);
const addInput=document.createElement('input');addInput.type='file';addInput.accept='image/*';addInput.multiple=true;addInput.style.display='none';document.body.appendChild(addInput);
const undoAction=document.createElement('button');undoAction.className='fastToastAction';undoAction.textContent='Deshacer';document.body.appendChild(undoAction);
const brief=document.createElement('div');brief.className='frameBriefBackdrop';brief.id='frameBrief';brief.innerHTML=`<div class="frameBriefCard"><div class="frameBriefEyebrow">Antes de diseñar</div><h3>¿Qué quieres que haga este post?</h3><div class="frameBriefIntro">Tres decisiones rápidas. FRAME usa esto para escoger la dirección, el ritmo y cuánto protagonismo darle a cada foto.</div><div class="briefQ"><b>1. ¿Qué quieres lograr?</b><div class="briefChoices" data-key="purpose"><button data-v="story" class="on">Contar una historia</button><button data-v="impact">Impactar</button><button data-v="memory">Guardar el momento</button><button data-v="showcase">Mostrar muchas fotos</button></div></div><div class="briefQ"><b>2. ¿Qué vibra buscas?</b><div class="briefChoices" data-key="vibe"><button data-v="clean" class="on">Editorial / limpio</button><button data-v="natural">Natural</button><button data-v="color">Color</button><button data-v="bold">Más atrevido</button></div></div><div class="briefQ"><b>3. ¿Cuánta información por slide?</b><div class="briefChoices briefDensity" data-key="density"><button data-v="airy">Con aire</button><button data-v="balanced" class="on">Equilibrado</button><button data-v="rich">Más fotos</button></div></div><div class="briefActions"><button id="briefSurprise">Sorpréndeme</button><button id="briefGo" class="primary">Diseñar ✦</button></div></div>`;document.body.appendChild(brief);
let busy=false,briefResolve=null,briefState={purpose:'story',vibe:'clean',density:'balanced'};
function setBusy(on){busy=on;qb.classList.toggle('busy',on);const eb=$('#emptyAdd');if(eb)eb.disabled=on}
function fire(primary,fallback){const a=$(primary);if(a){a.click();return true}const b=fallback?$(fallback):null;if(b){b.click();return true}return false}
function hideClutter(){const bar=$('#controlBar');if(bar)bar.classList.add('speedHidden');$('#randomBtn')?.classList.add('speedHidden');$('#slideBtn')?.classList.add('speedHidden')}
function emptyState(){const isEmpty=!S.photos?.length||!S.slides?.length;studio?.classList.toggle('emptyStateFast',isEmpty);empty.classList.toggle('on',isEmpty);if(isEmpty){const count=studio?.querySelector('.studioTop small');if(count)count.textContent='Nuevo proyecto'}return isEmpty}
hideClutter();emptyState();
function remember(){prefs.slides=S.slides?.length||prefs.slides;localStorage.setItem(PREF,JSON.stringify(prefs))}
function snapshot(){return clone({slides:S.slides,currentSlide:S.currentSlide,randomMode:S.randomMode,showSafe:S.showSafe,finish:S.finish,designDNA:S.designDNA,frameBrief:S.frameBrief})}
let quickUndo=null,undoTimer=null;function offerUndo(snap,label){quickUndo=snap;undoAction.classList.add('on');clearTimeout(undoTimer);undoTimer=setTimeout(()=>undoAction.classList.remove('on'),3000);toast(label)}undoAction.onclick=()=>{if(!quickUndo||busy)return;Object.assign(S,quickUndo);quickUndo=null;undoAction.classList.remove('on');renderAll();saveProject();toast('Deshecho')};
function syncBriefUI(){brief.querySelectorAll('[data-key]').forEach(group=>{const key=group.dataset.key;group.querySelectorAll('button').forEach(b=>b.classList.toggle('on',briefState[key]===b.dataset.v))})}
brief.addEventListener('click',e=>{const b=e.target.closest('[data-key] button');if(!b)return;const g=b.closest('[data-key]');briefState[g.dataset.key]=b.dataset.v;syncBriefUI()});
function askBrief(){briefState={purpose:'story',vibe:'clean',density:'balanced'};syncBriefUI();brief.classList.add('on');return new Promise(resolve=>{briefResolve=resolve})}
$('#briefGo').onclick=()=>{brief.classList.remove('on');const r=briefResolve;briefResolve=null;r?.({...briefState})};
$('#briefSurprise').onclick=()=>{brief.classList.remove('on');const r=briefResolve;briefResolve=null;r?.({purpose:'surprise',vibe:'surprise',density:'balanced'})};
$('#fastNewDesign').onclick=()=>{if(busy)return;if(emptyState()){addInput.click();return}const snap=snapshot();setBusy(true);requestAnimationFrame(()=>{try{if(typeof window.FRAME_rebuildStory==='function')window.FRAME_rebuildStory();else fire('#directorBtn','#randomBtn');remember();offerUndo(snap,'Otra opción lista')}finally{setTimeout(()=>setBusy(false),180)}})};
$('#fastExport').onclick=()=>{if(busy)return;if(emptyState()){addInput.click();return}if(!fire('#exportAllBtn','#exportBtn'))toast('Exportar no está disponible')};$('#fastAdd').onclick=()=>{if(!busy)addInput.click()};$('#emptyAdd').onclick=()=>{if(!busy)addInput.click()};
const clamp01=v=>Math.max(0,Math.min(1,Number(v)||0));
function loadScriptOnce(src){return new Promise((res,rej)=>{const existing=[...document.scripts].find(s=>s.src===src);if(existing){if(existing.dataset.ready==='1'||window.FaceDetection)return res();existing.addEventListener('load',res,{once:true});existing.addEventListener('error',rej,{once:true});return}const s=document.createElement('script');s.src=src;s.async=true;s.onload=()=>{s.dataset.ready='1';res()};s.onerror=rej;document.head.appendChild(s)})}
function loadPhoto(url){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=url})}
let detectorPromise=null;
function getFaceDetector(){if(detectorPromise)return detectorPromise;detectorPromise=(async()=>{try{await loadScriptOnce('https://cdn.jsdelivr.net/npm/@mediapipe/face_detection/face_detection.js');if(!window.FaceDetection)return null;const fd=new FaceDetection({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/face_detection/${f}`});fd.setOptions({model:'short',minDetectionConfidence:.52});let pending=null;fd.onResults(r=>{if(pending){const fn=pending;pending=null;fn(r)}});fd.__frameSend=image=>new Promise(resolve=>{const timer=setTimeout(()=>{pending=null;resolve(null)},2800);pending=r=>{clearTimeout(timer);resolve(r)};Promise.resolve(fd.send({image})).catch(()=>{clearTimeout(timer);pending=null;resolve(null)})});return fd}catch(e){console.warn('face detector unavailable',e);return null}})();return detectorPromise}
function boxFromDetection(d){const b=d?.locationData?.relativeBoundingBox||d?.relativeBoundingBox||null;if(!b)return null;const x=clamp01(b.xMin??b.x??0),y=clamp01(b.yMin??b.y??0),w=clamp01(b.width??0),h=clamp01(b.height??0);if(w<.02||h<.02)return null;return{x,y,w:Math.min(w,1-x),h:Math.min(h,1-y),score:Number(d?.score?.[0]??d?.score??0)}}
function unionFaces(faces){if(!faces.length)return null;const x1=Math.min(...faces.map(f=>f.x)),y1=Math.min(...faces.map(f=>f.y)),x2=Math.max(...faces.map(f=>f.x+f.w)),y2=Math.max(...faces.map(f=>f.y+f.h));return{x:x1,y:y1,w:x2-x1,h:y2-y1,cx:(x1+x2)/2,cy:(y1+y2)/2}}
async function enrichComposition(p){try{const im=await loadPhoto(p.url);p.width=im.naturalWidth||im.width;p.height=im.naturalHeight||im.height;if(p.width&&p.height)p.aspect=p.width/p.height;const max=512,scale=Math.min(1,max/Math.max(p.width||1,p.height||1)),cv=document.createElement('canvas');cv.width=Math.max(1,Math.round((p.width||1)*scale));cv.height=Math.max(1,Math.round((p.height||1)*scale));cv.getContext('2d',{willReadFrequently:false}).drawImage(im,0,0,cv.width,cv.height);const fd=await getFaceDetector();let faces=[];if(fd?.__frameSend){const r=await fd.__frameSend(cv);faces=(r?.detections||[]).map(boxFromDetection).filter(Boolean).filter(f=>f.score===0||f.score>=.45)}p.faces=faces;p.faceCount=faces.length;p.faceUnion=unionFaces(faces);p.faceCenter=p.faceUnion?{x:p.faceUnion.cx,y:p.faceUnion.cy}:null;p.hasFaces=faces.length>0;return p}catch(e){console.warn('composition analysis',p?.name,e);p.faces=p.faces||[];p.faceCount=p.faces.length;p.faceUnion=unionFaces(p.faces);return p}}
async function analyzeFiles(files){const out=new Array(files.length);let next=0,done=0;const workers=Math.min(3,files.length),eb=$('#emptyAdd');async function worker(){while(true){const i=next++;if(i>=files.length)return;const f=files[i];try{const p={id:uid(),name:f.name,url:URL.createObjectURL(f)};out[i]=await analyzePhoto(p)}catch(err){console.warn('photo',f.name,err)}finally{done++;if(eb)eb.textContent=`Analizando ${done}/${files.length}`;await new Promise(r=>setTimeout(r,0))}}}await Promise.all(Array.from({length:workers},worker));const list=out.filter(Boolean);for(let i=0;i<list.length;i++){if(eb)eb.textContent=`Leyendo composición ${i+1}/${list.length}`;await enrichComposition(list[i]);await new Promise(r=>setTimeout(r,0))}return list}
addInput.onchange=async e=>{const files=[...e.target.files];if(!files.length||busy)return;const loading=$('#loading'),eb=$('#emptyAdd'),oldText=eb?.textContent,firstProject=!S.photos?.length;setBusy(true);loading?.classList.add('on');try{const analyzed=await analyzeFiles(files);if(!analyzed.length)throw new Error('No photos analyzed');if(firstProject){loading?.classList.remove('on');S.frameBrief=await askBrief();loading?.classList.add('on')}S.photos.push(...analyzed);buildSlides();renderAll();saveProject();toast(`${analyzed.length} foto${analyzed.length>1?'s':''} lista${analyzed.length>1?'s':''}`)}catch(err){console.warn(err);toast('No pude añadir esas fotos')}finally{loading?.classList.remove('on');addInput.value='';if(eb)eb.textContent=oldText||'＋ Elegir fotos';setBusy(false);emptyState()}};
const exportTool=$('#exportBtn');if(exportTool){let hold=false,timer;exportTool.onclick=null;exportTool.addEventListener('touchstart',()=>{hold=false;timer=setTimeout(()=>{hold=true;openSheet('#exportSheet')},520)},{passive:true});exportTool.addEventListener('touchend',e=>{clearTimeout(timer);if(!hold){e.preventDefault();fire('#exportAllBtn')}},{passive:false})}
const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();requestAnimationFrame(emptyState)};const oldSave=saveProject;saveProject=function(){oldSave();remember()};remember();
})();