(()=>{
const CW=340, CH=425;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const pick=a=>a[Math.floor(Math.random()*a.length)];
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
const scorePhoto=p=>Number(p?.score||0);
const imgLayers=sl=>(sl.layers||[]).filter(l=>l.type==='img'&&!l.hidden);
const cloneImg=(t,p,o={})=>{const l=clone(t);Object.assign(l,{id:uid(),type:'img',photo:p,hidden:false,locked:false,userTouched:true,storyAuto:true,rot:0,zoom:1,offX:0,offY:0,z:10},o);return l};
function template(){return S.slides?.flatMap(s=>s.layers||[]).find(l=>l.type==='img')||null}
function ppal(p){try{return palFromPhoto(p)}catch(e){return [[24,24,26],[240,238,232],[128,128,132],[195,92,70]]}}
function rgb(c){return Array.isArray(c)?`rgb(${Math.round(c[0])},${Math.round(c[1])},${Math.round(c[2])})`:c}
function mix(a,b,t){return [0,1,2].map(i=>Math.round((a?.[i]??0)*(1-t)+(b?.[i]??0)*t))}
function lum(c){return Array.isArray(c)?c[0]*.299+c[1]*.587+c[2]*.114:128}
function sat(c){if(!Array.isArray(c))return 0;const mx=Math.max(...c),mn=Math.min(...c);return mx-mn}
function photoMeta(p){const aspect=Number(p?.aspect||p?.ratio||1);const g=Array.isArray(p?.grid)?p.grid.map(Number):null;let quiet='bottom',activity=0.5;if(g?.length>=9){const z={top:(g[0]+g[1]+g[2])/3,bottom:(g[6]+g[7]+g[8])/3,left:(g[0]+g[3]+g[6])/3,right:(g[2]+g[5]+g[8])/3};quiet=Object.entries(z).sort((a,b)=>a[1]-b[1])[0][0];activity=g.reduce((a,b)=>a+b,0)/g.length}return{aspect,portrait:aspect<.82,landscape:aspect>1.18,square:aspect>=.82&&aspect<=1.18,quiet,activity,score:scorePhoto(p),variance:Number(p?.variance||0),avg:p?.avg||[128,128,128]}}
function setPalette(photos){const cols=[];photos.forEach(p=>{const pp=ppal(p);pp.slice(0,4).forEach(c=>{if(Array.isArray(c))cols.push(c)})});if(!cols.length)return{canvas:[242,239,232],surface:[20,20,22],ink:[18,18,20],accent:[176,92,70],accentSoft:[222,196,184],dark:[13,13,15],light:[244,241,235]};const light=[...cols].sort((a,b)=>lum(b)-lum(a))[0],dark=[...cols].sort((a,b)=>lum(a)-lum(b))[0],accent=[...cols].sort((a,b)=>sat(b)-sat(a))[0];const avg=cols.reduce((r,c)=>r.map((v,i)=>v+c[i]),[0,0,0]).map(v=>v/cols.length);const canvas=lum(avg)>125?mix(avg,[248,246,240],.78):mix(avg,[244,241,234],.9);return{canvas,surface:mix(dark,[18,18,20],.65),ink:lum(canvas)>145?[18,18,20]:[245,243,238],accent,accentSoft:mix(accent,canvas,.72),dark:mix(dark,[9,9,11],.6),light:mix(light,[247,244,238],.75)}}
const DIRECTIONS={
 editorial:{name:'editorial',density:.45,spread:.66,three:.12,bg:'neutral',layouts:['gallery','full','offset','split','duo'],heroBias:.9},
 chromatic:{name:'chromatic',density:.62,spread:.54,three:.18,bg:'color',layouts:['colorFrame','split','mosaic','full','duo'],heroBias:.78},
 documentary:{name:'documentary',density:.34,spread:.76,three:.2,bg:'dark',layouts:['full','full','split','wideBand','gallery'],heroBias:.96},
 journal:{name:'journal',density:.58,spread:.4,three:.08,bg:'light',layouts:['gallery','offset','duo','stack','contact'],heroBias:.72},
 bold:{name:'bold',density:.7,spread:.58,three:.22,bg:'contrast',layouts:['edge','split','mosaic','full','colorFrame'],heroBias:.86},
 soft:{name:'soft',density:.38,spread:.46,three:.05,bg:'soft',layouts:['gallery','offset','full','duo','wideBand'],heroBias:.74},
 collage:{name:'collage',density:.8,spread:.28,three:.04,bg:'light',layouts:['mosaic','contact','duo','stack','split'],heroBias:.58}
};
function chooseDirection(){const keys=Object.keys(DIRECTIONS),prev=S.frameArtDirection;const pool=keys.filter(k=>k!==prev);const key=pick(pool.length?pool:keys);S.frameArtDirection=key;return DIRECTIONS[key]}
function bgFor(dir,pal,p,variant=0){if(dir.bg==='dark')return rgb(pal.dark);if(dir.bg==='light')return rgb(pal.light);if(dir.bg==='soft')return rgb(pal.canvas);if(dir.bg==='color')return variant%2?rgb(pal.accentSoft):rgb(pal.canvas);if(dir.bg==='contrast')return variant%2?rgb(pal.dark):rgb(pal.light);return lum(photoMeta(p).avg)<105?rgb(pal.dark):rgb(pal.canvas)}
function wipe(sl){const manual=(sl.layers||[]).filter(l=>l.type==='text'&&l.userTouched);sl.layers=manual;sl.storySpan=null;sl.frameAuto=true}
function full(sl,t,p,ctx){sl.bg=bgFor(ctx.dir,ctx.pal,p,ctx.i);sl.layers.push(cloneImg(t,p,{x:0,y:0,w:CW,h:CH}))}
function gallery(sl,t,p,ctx){sl.bg=bgFor(ctx.dir,ctx.pal,p,ctx.i);const m=photoMeta(p);const px=ctx.dir.name==='soft'?30:20;const py=m.landscape?58:22;sl.layers.push(cloneImg(t,p,{x:px,y:py,w:CW-px*2,h:m.landscape?304:CH-py*2}))}
function offset(sl,t,p,ctx){sl.bg=bgFor(ctx.dir,ctx.pal,p,ctx.i+1);const m=photoMeta(p);if(m.portrait){const left=ctx.i%2?68:18;sl.layers.push(cloneImg(t,p,{x:left,y:18,w:254,h:389}))}else{sl.layers.push(cloneImg(t,p,{x:18,y:ctx.i%2?88:36,w:304,h:296}))}}
function split(sl,t,a,b,ctx){sl.bg=bgFor(ctx.dir,ctx.pal,a,ctx.i);const A=photoMeta(a),B=photoMeta(b);if(A.portrait&&B.portrait){sl.layers.push(cloneImg(t,a,{x:14,y:18,w:151,h:389}));sl.layers.push(cloneImg(t,b,{x:175,y:18,w:151,h:389,z:11}))}else if(ctx.i%2===0){sl.layers.push(cloneImg(t,a,{x:0,y:0,w:214,h:CH}));sl.layers.push(cloneImg(t,b,{x:224,y:56,w:116,h:313,z:11}))}else{sl.layers.push(cloneImg(t,a,{x:18,y:18,w:304,h:250}));sl.layers.push(cloneImg(t,b,{x:86,y:280,w:236,h:127,z:11}))}}
function duo(sl,t,a,b,ctx){sl.bg=bgFor(ctx.dir,ctx.pal,a,ctx.i+1);if(ctx.i%2){sl.layers.push(cloneImg(t,a,{x:18,y:18,w:304,h:238}));sl.layers.push(cloneImg(t,b,{x:176,y:270,w:146,h:137,z:11}))}else{sl.layers.push(cloneImg(t,a,{x:0,y:0,w:CW,h:256}));sl.layers.push(cloneImg(t,b,{x:20,y:276,w:300,h:131,z:11}))}}
function mosaic(sl,t,a,b,c,ctx){sl.bg=bgFor(ctx.dir,ctx.pal,a,ctx.i);if(ctx.i%2){sl.layers.push(cloneImg(t,a,{x:18,y:18,w:304,h:235}));sl.layers.push(cloneImg(t,b,{x:18,y:266,w:145,h:141,z:11}));sl.layers.push(cloneImg(t,c,{x:177,y:266,w:145,h:141,z:12}))}else{sl.layers.push(cloneImg(t,a,{x:0,y:0,w:218,h:CH}));sl.layers.push(cloneImg(t,b,{x:228,y:0,w:112,h:207,z:11}));sl.layers.push(cloneImg(t,c,{x:228,y:217,w:112,h:208,z:12}))}}
function colorFrame(sl,t,p,ctx){sl.bg=rgb(ctx.i%2?ctx.pal.accentSoft:ctx.pal.accent);const m=photoMeta(p);const pad=m.portrait?28:18;sl.layers.push(cloneImg(t,p,{x:pad,y:m.portrait?24:56,w:CW-pad*2,h:m.portrait?377:313}))}
function edge(sl,t,p,ctx){sl.bg=rgb(ctx.i%2?ctx.pal.dark:ctx.pal.light);const side=ctx.i%2;sl.layers.push(cloneImg(t,p,{x:side?66:0,y:0,w:274,h:CH}))}
function wideBand(sl,t,p,ctx){sl.bg=bgFor(ctx.dir,ctx.pal,p,ctx.i);sl.layers.push(cloneImg(t,p,{x:0,y:78,w:CW,h:269}))}
function stack(sl,t,a,b,ctx){sl.bg=bgFor(ctx.dir,ctx.pal,a,ctx.i);sl.layers.push(cloneImg(t,a,{x:18,y:18,w:304,h:185}));sl.layers.push(cloneImg(t,b,{x:18,y:222,w:304,h:185,z:11}))}
function contact(sl,t,set,ctx){sl.bg=bgFor(ctx.dir,ctx.pal,set[0],ctx.i);const gap=8,w=(CW-36-gap)/2,h=(CH-36-gap)/2;set.slice(0,4).forEach((p,k)=>sl.layers.push(cloneImg(t,p,{x:14+(k%2)*(w+gap),y:14+Math.floor(k/2)*(h+gap),w,h,z:10+k}))) }
function spread(slides,start,span,t,p,ctx){for(let i=0;i<span;i++){const sl=slides[start+i];sl.bg=ctx.dir.bg==='light'?rgb(ctx.pal.light):rgb(ctx.pal.dark);sl.storySpan={photoId:p.id,start,span,seg:i};sl.layers.push(cloneImg(t,p,{x:-CW*i,y:0,w:CW*span,h:CH,storySpan:true,storySeg:i,storySpanCount:span}))}}
function desiredSlides(n,dir,span){if(n<=3)return n;const targetPhotosPerSlide=1.15+dir.density*1.45;return clamp(Math.ceil((n+(span-1))/targetPhotosPerSlide),4,10)}
function heroFrom(photos,dir){const sorted=[...photos].sort((a,b)=>scorePhoto(b)-scorePhoto(a));const top=sorted.slice(0,Math.min(4,sorted.length));return Math.random()<dir.heroBias?top[0]:pick(top)}
function layoutTake(kind){return ['mosaic','contact'].includes(kind)?3:['split','duo','stack'].includes(kind)?2:1}
function compatible(kind,set){if(!set.length)return false;if(kind==='contact'||kind==='mosaic')return set.length>=3;if(['split','duo','stack'].includes(kind))return set.length>=2;return true}
function applyLayout(kind,sl,t,set,ctx){if(kind==='full')full(sl,t,set[0],ctx);else if(kind==='gallery')gallery(sl,t,set[0],ctx);else if(kind==='offset')offset(sl,t,set[0],ctx);else if(kind==='split')split(sl,t,set[0],set[1],ctx);else if(kind==='duo')duo(sl,t,set[0],set[1],ctx);else if(kind==='mosaic')mosaic(sl,t,set[0],set[1],set[2],ctx);else if(kind==='colorFrame')colorFrame(sl,t,set[0],ctx);else if(kind==='edge')edge(sl,t,set[0],ctx);else if(kind==='wideBand')wideBand(sl,t,set[0],ctx);else if(kind==='stack')stack(sl,t,set[0],set[1],ctx);else contact(sl,t,set,ctx)}
function makeCandidate(photos,t,dir,palette){const hero=heroFrom(photos,dir);let span=1;if(photos.length>=9&&Math.random()<dir.spread)span=Math.random()<dir.three?3:2;else if(photos.length>=6&&Math.random()<dir.spread)span=2;const count=desiredSlides(photos.length,dir,span);const slides=Array.from({length:count},()=>({id:uid(),layers:[],bg:'#0b0b0d',palette:null,frameAuto:true}));slides.forEach(wipe);const occupied=new Set();if(span>1&&count>=span+2){const start=Math.min(Math.floor(Math.random()*Math.min(3,count-span+1)),count-span);spread(slides,start,span,t,hero,{dir,pal:palette,i:start});for(let i=0;i<span;i++)occupied.add(start+i)}
 const rest=shuffle(span>1?photos.filter(p=>p.id!==hero.id):photos);let cursor=0,prevKind='';
 for(let si=0;si<count;si++){if(occupied.has(si))continue;const sl=slides[si],remaining=rest.length-cursor;if(remaining<=0)break;const candidates=shuffle(dir.layouts.filter(k=>k!==prevKind));let chosen=candidates.find(k=>compatible(k,rest.slice(cursor,cursor+layoutTake(k))))||'full';let take=Math.min(layoutTake(chosen),remaining);if(remaining===1){chosen=['full','gallery','offset','colorFrame','edge','wideBand'].includes(chosen)?chosen:'full';take=1}else if(remaining===2&&take===3){chosen='split';take=2}const set=rest.slice(cursor,cursor+take);cursor+=take;sl.palette=ppal(set[0]);applyLayout(chosen,sl,t,set,{dir,pal:palette,i:si});prevKind=chosen;sl.frameLayout=chosen;}
 const used=new Set(slides.flatMap(imgLayers).map(l=>l.photo?.id).filter(Boolean));for(const p of photos){if(used.has(p.id))continue;const target=slides.find((s,i)=>!occupied.has(i)&&imgLayers(s).length<3)||slides[slides.length-1];const n=imgLayers(target).length;target.layers.push(cloneImg(t,p,{x:n===0?18:n===1?177:228,y:n===0?18:n===1?266:217,w:n===0?304:n===1?145:112,h:n===0?235:n===1?141:208,z:15+n}));used.add(p.id)}
 slides.forEach(sl=>{sl.layers=sl.layers.filter(l=>l.type==='img'||(l.type==='text'&&l.userTouched))});return{slides,hero,span,dir:dir.name,palette};}
function scoreCandidate(c,photos,prev){let s=100;const layouts=c.slides.map(sl=>sl.frameLayout||'spread');s+=new Set(layouts).size*5;for(let i=1;i<layouts.length;i++)if(layouts[i]===layouts[i-1])s-=10;const counts=c.slides.map(sl=>imgLayers(sl).length);if(counts.filter(n=>n>=3).length>Math.ceil(c.slides.length*.45))s-=14;if(c.span>1)s+=8;const used=new Set(c.slides.flatMap(imgLayers).map(l=>l.photo?.id).filter(Boolean));s-=Math.max(0,photos.length-used.size)*25;const bgs=c.slides.map(sl=>sl.bg);for(let i=1;i<bgs.length;i++)if(bgs[i]===bgs[i-1]&&layouts[i]===layouts[i-1])s-=4;if(prev){if(prev.dir===c.dir)s-=30;if((prev.layouts||[]).join('|')===layouts.join('|'))s-=40;if(prev.heroId&&prev.heroId===c.hero?.id)s-=8}return s+Math.random()*5}
function buildStory(){if(!S.photos?.length)return;const t=template();if(!t)return;const photos=[...S.photos],palette=setPalette(photos),dir=chooseDirection(),prev=S.frameLastDesign||null,candidates=[];for(let i=0;i<8;i++){const c=makeCandidate(photos,t,dir,palette);c.score=scoreCandidate(c,photos,prev);candidates.push(c)}candidates.sort((a,b)=>b.score-a.score);const chosen=pick(candidates.slice(0,Math.min(3,candidates.length)));S.slides=chosen.slides;S.framePalette=chosen.palette;S.frameArtDirection=chosen.dir;S.frameLastDesign={dir:chosen.dir,heroId:chosen.hero?.id||null,layouts:chosen.slides.map(sl=>sl.frameLayout||'spread')};S.currentSlide=Math.min(S.currentSlide||0,S.slides.length-1);S.selected=null;S.selectedType=null;saveProject();}
window.FRAME_rebuildStory=()=>{try{if(typeof pushHistory==='function')pushHistory()}catch(e){}buildStory();renderAll();saveProject();toast('Nueva dirección ✦')};
const prevBuild=buildSlides;buildSlides=function(){prevBuild();buildStory()};
const style=document.createElement('style');style.textContent='#storyBadge,.storyBadge,.coverageBadge{display:none!important}';document.head.appendChild(style);
if(S.photos?.length){buildStory();renderAll()}
})();