(()=>{
const CW=340,CH=425,AREA=CW*CH;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const pick=a=>a[Math.floor(Math.random()*a.length)];
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
const scorePhoto=p=>Number(p?.score||0);
const imgLayers=sl=>(sl.layers||[]).filter(l=>l.type==='img'&&!l.hidden);
function template(){return S.slides?.flatMap(s=>s.layers||[]).find(l=>l.type==='img')||null}
function ppal(p){try{return palFromPhoto(p)}catch(e){return [[24,24,26],[240,238,232],[128,128,132],[195,92,70]]}}
function rgb(c){return Array.isArray(c)?`rgb(${Math.round(c[0])},${Math.round(c[1])},${Math.round(c[2])})`:c}
function mix(a,b,t){return [0,1,2].map(i=>Math.round((a?.[i]??0)*(1-t)+(b?.[i]??0)*t))}
function lum(c){return Array.isArray(c)?c[0]*.299+c[1]*.587+c[2]*.114:128}
function sat(c){if(!Array.isArray(c))return 0;return Math.max(...c)-Math.min(...c)}
function faceUnion(p){if(p?.faceUnion)return p.faceUnion;const f=Array.isArray(p?.faces)?p.faces:[];if(!f.length)return null;const x1=Math.min(...f.map(x=>x.x)),y1=Math.min(...f.map(x=>x.y)),x2=Math.max(...f.map(x=>x.x+x.w)),y2=Math.max(...f.map(x=>x.y+x.h));return{x:x1,y:y1,w:x2-x1,h:y2-y1,cx:(x1+x2)/2,cy:(y1+y2)/2}}
function photoMeta(p){const aspect=Number(p?.aspect||p?.ratio||(p?.width&&p?.height?p.width/p.height:1))||1,g=Array.isArray(p?.grid)?p.grid.map(Number):null;let quiet='bottom',activity=.5;if(g?.length>=9){const z={top:(g[0]+g[1]+g[2])/3,bottom:(g[6]+g[7]+g[8])/3,left:(g[0]+g[3]+g[6])/3,right:(g[2]+g[5]+g[8])/3};quiet=Object.entries(z).sort((a,b)=>a[1]-b[1])[0][0];activity=g.reduce((a,b)=>a+b,0)/g.length}const faces=Array.isArray(p?.faces)?p.faces:[],union=faceUnion(p),faceCount=Number.isFinite(p?.faceCount)?p.faceCount:faces.length;return{aspect,portrait:aspect<.82,landscape:aspect>1.18,square:aspect>=.82&&aspect<=1.18,quiet,activity,score:scorePhoto(p),variance:Number(p?.variance||0),avg:p?.avg||[128,128,128],faces,faceCount,faceUnion:union}}
function setPalette(photos){const cols=[];photos.forEach(p=>ppal(p).slice(0,4).forEach(c=>Array.isArray(c)&&cols.push(c)));if(!cols.length)return{canvas:[242,239,232],surface:[20,20,22],ink:[18,18,20],accent:[176,92,70],accentSoft:[222,196,184],dark:[13,13,15],light:[244,241,235]};const light=[...cols].sort((a,b)=>lum(b)-lum(a))[0],dark=[...cols].sort((a,b)=>lum(a)-lum(b))[0];const useful=cols.filter(c=>lum(c)>40&&lum(c)<225),accent=[...(useful.length?useful:cols)].sort((a,b)=>sat(b)-sat(a))[0];const avg=cols.reduce((r,c)=>r.map((v,i)=>v+c[i]),[0,0,0]).map(v=>v/cols.length),canvas=lum(avg)>125?mix(avg,[248,246,240],.8):mix(avg,[244,241,234],.9);return{canvas,surface:mix(dark,[18,18,20],.68),ink:lum(canvas)>145?[18,18,20]:[245,243,238],accent:mix(accent,lum(accent)>150?[115,105,100]:[235,225,215],.16),accentSoft:mix(accent,canvas,.76),dark:mix(dark,[9,9,11],.62),light:mix(light,[247,244,238],.78)}}
const DIRECTIONS={
 editorial:{name:'editorial',density:.43,spread:.68,three:.1,bg:'neutral',layouts:['gallery','full','offset','split','duo'],heroBias:.9},
 chromatic:{name:'chromatic',density:.6,spread:.5,three:.14,bg:'color',layouts:['colorFrame','split','mosaic','full','duo'],heroBias:.78},
 documentary:{name:'documentary',density:.32,spread:.78,three:.16,bg:'dark',layouts:['full','full','split','wideBand','gallery'],heroBias:.96},
 journal:{name:'journal',density:.56,spread:.38,three:.05,bg:'light',layouts:['gallery','offset','duo','stack','contact'],heroBias:.72},
 bold:{name:'bold',density:.66,spread:.56,three:.16,bg:'contrast',layouts:['edge','split','mosaic','full','colorFrame'],heroBias:.86},
 soft:{name:'soft',density:.36,spread:.43,three:.03,bg:'soft',layouts:['gallery','offset','full','duo','wideBand'],heroBias:.74},
 collage:{name:'collage',density:.76,spread:.25,three:.02,bg:'light',layouts:['mosaic','contact','duo','stack','split'],heroBias:.58}
};
function chooseDirection(){const keys=Object.keys(DIRECTIONS),prev=S.frameArtDirection,pool=keys.filter(k=>k!==prev);const key=pick(pool.length?pool:keys);return DIRECTIONS[key]}
function bgFor(dir,pal,p,v=0){if(dir.bg==='dark')return rgb(pal.dark);if(dir.bg==='light')return rgb(pal.light);if(dir.bg==='soft')return rgb(pal.canvas);if(dir.bg==='color')return v%2?rgb(pal.accentSoft):rgb(pal.canvas);if(dir.bg==='contrast')return v%2?rgb(pal.dark):rgb(pal.light);return lum(photoMeta(p).avg)<105?rgb(pal.dark):rgb(pal.canvas)}
function focusProps(p,w,h){const m=photoMeta(p),u=m.faceUnion;if(!u)return{offX:0,offY:0};const cx=Number.isFinite(u.cx)?u.cx:u.x+u.w/2,cy=Number.isFinite(u.cy)?u.cy:u.y+u.h/2;const strength=m.faceCount>=3?52:68;return{offX:clamp((cx-.5)*strength,-28,28),offY:clamp((cy-.5)*strength,-24,24)}}
function cloneImg(t,p,o={}){const l=clone(t);Object.assign(l,{id:uid(),type:'img',photo:p,hidden:false,locked:false,userTouched:true,storyAuto:true,rot:0,zoom:1,offX:0,offY:0,z:10},o);if(o.w&&o.h){const f=focusProps(p,o.w,o.h);l.offX=f.offX;l.offY=f.offY}return l}
function faceFit(p,w,h){const m=photoMeta(p),u=m.faceUnion;if(!u||!m.faceCount)return 1;const fa=w/h,sa=m.aspect;let visW=1,visH=1;if(sa>fa)visW=clamp(fa/sa,.05,1);else visH=clamp(sa/fa,.05,1);const rw=u.w/Math.max(.01,visW*.88),rh=u.h/Math.max(.01,visH*.88),need=Math.max(rw,rh);return clamp(1-Math.max(0,need-1)*1.7,0,1)}
function slotScore(p,w,h,role='normal'){const m=photoMeta(p),fa=w/h,area=w*h/AREA;let s=scorePhoto(p)*7;const aspectMatch=Math.exp(-Math.abs(Math.log(Math.max(.08,m.aspect)/Math.max(.08,fa))));s+=aspectMatch*18;const ff=faceFit(p,w,h);if(m.faceCount)s+=ff*42-(1-ff)*72;if(m.faceCount>=3&&area<.42)s-=65;if(m.faceCount===2&&area<.25)s-=30;if(m.activity>.72&&area<.2)s-=15;if(role==='wide'){s+=m.landscape?24:m.portrait?-28:5;if(m.faceCount>=3)s+=8}if(role==='portrait'){s+=m.portrait?24:m.landscape?-22:4;if(m.faceCount===1)s+=12;if(m.faceCount>=3)s-=35}if(role==='small'){if(m.faceCount>=2)s-=48;else if(!m.faceCount)s+=9;if(m.activity<.42)s+=6}if(role==='hero'){s+=scorePhoto(p)*12;if(m.faceCount>=2)s+=4}if(role==='spread'){s+=m.landscape?38:m.portrait?-110:-12;if(m.aspect>1.45)s+=18;if(ff<.78)s-=60}return s}
const HINTS={
 full:[{w:340,h:425,r:'hero'}],gallery:[{w:300,h:360,r:'hero'}],offset:[{w:254,h:389,r:'portrait'}],colorFrame:[{w:284,h:360,r:'hero'}],edge:[{w:274,h:425,r:'portrait'}],wideBand:[{w:340,h:269,r:'wide'}],
 split:[{w:214,h:425,r:'hero'},{w:116,h:313,r:'small'}],duo:[{w:304,h:238,r:'hero'},{w:146,h:137,r:'small'}],stack:[{w:304,h:185,r:'wide'},{w:304,h:185,r:'wide'}],mosaic:[{w:218,h:425,r:'hero'},{w:112,h:207,r:'small'},{w:112,h:208,r:'small'}],contact:[{w:151,h:190,r:'small'},{w:151,h:190,r:'small'},{w:151,h:190,r:'small'},{w:151,h:190,r:'small'}]
};
function layoutTake(k){return HINTS[k]?.length||1}
function assignFor(kind,pool){const hints=HINTS[kind]||HINTS.full;if(pool.length<hints.length)return null;const left=[...pool],set=[],scores=[];for(const h of hints){let ranked=left.map(p=>({p,s:slotScore(p,h.w,h.h,h.r)+Math.random()*2.2})).sort((a,b)=>b.s-a.s);const best=ranked[0];if(!best)return null;set.push(best.p);scores.push(best.s);left.splice(left.indexOf(best.p),1)}return{set,fit:scores.reduce((a,b)=>a+b,0)/scores.length}}
function full(sl,t,p,c){sl.bg=bgFor(c.dir,c.pal,p,c.i);sl.layers.push(cloneImg(t,p,{x:0,y:0,w:CW,h:CH}))}
function gallery(sl,t,p,c){sl.bg=bgFor(c.dir,c.pal,p,c.i);const m=photoMeta(p),px=c.dir.name==='soft'?30:20,py=m.landscape?58:22;sl.layers.push(cloneImg(t,p,{x:px,y:py,w:CW-px*2,h:m.landscape?304:CH-py*2}))}
function offset(sl,t,p,c){sl.bg=bgFor(c.dir,c.pal,p,c.i+1);const m=photoMeta(p);if(m.portrait)sl.layers.push(cloneImg(t,p,{x:c.i%2?68:18,y:18,w:254,h:389}));else sl.layers.push(cloneImg(t,p,{x:18,y:c.i%2?88:36,w:304,h:296}))}
function split(sl,t,a,b,c){sl.bg=bgFor(c.dir,c.pal,a,c.i);const A=photoMeta(a),B=photoMeta(b);if(A.portrait&&B.portrait&&A.faceCount<3&&B.faceCount<3){sl.layers.push(cloneImg(t,a,{x:14,y:18,w:151,h:389}));sl.layers.push(cloneImg(t,b,{x:175,y:18,w:151,h:389,z:11}))}else if(c.i%2===0){sl.layers.push(cloneImg(t,a,{x:0,y:0,w:214,h:CH}));sl.layers.push(cloneImg(t,b,{x:224,y:56,w:116,h:313,z:11}))}else{sl.layers.push(cloneImg(t,a,{x:18,y:18,w:304,h:250}));sl.layers.push(cloneImg(t,b,{x:86,y:280,w:236,h:127,z:11}))}}
function duo(sl,t,a,b,c){sl.bg=bgFor(c.dir,c.pal,a,c.i+1);if(c.i%2){sl.layers.push(cloneImg(t,a,{x:18,y:18,w:304,h:238}));sl.layers.push(cloneImg(t,b,{x:176,y:270,w:146,h:137,z:11}))}else{sl.layers.push(cloneImg(t,a,{x:0,y:0,w:CW,h:256}));sl.layers.push(cloneImg(t,b,{x:20,y:276,w:300,h:131,z:11}))}}
function mosaic(sl,t,a,b,d,c){sl.bg=bgFor(c.dir,c.pal,a,c.i);if(c.i%2){sl.layers.push(cloneImg(t,a,{x:18,y:18,w:304,h:235}));sl.layers.push(cloneImg(t,b,{x:18,y:266,w:145,h:141,z:11}));sl.layers.push(cloneImg(t,d,{x:177,y:266,w:145,h:141,z:12}))}else{sl.layers.push(cloneImg(t,a,{x:0,y:0,w:218,h:CH}));sl.layers.push(cloneImg(t,b,{x:228,y:0,w:112,h:207,z:11}));sl.layers.push(cloneImg(t,d,{x:228,y:217,w:112,h:208,z:12}))}}
function colorFrame(sl,t,p,c){sl.bg=rgb(c.i%2?c.pal.accentSoft:c.pal.accent);const m=photoMeta(p),pad=m.portrait?28:18;sl.layers.push(cloneImg(t,p,{x:pad,y:m.portrait?24:56,w:CW-pad*2,h:m.portrait?377:313}))}
function edge(sl,t,p,c){sl.bg=rgb(c.i%2?c.pal.dark:c.pal.light);sl.layers.push(cloneImg(t,p,{x:c.i%2?66:0,y:0,w:274,h:CH}))}
function wideBand(sl,t,p,c){sl.bg=bgFor(c.dir,c.pal,p,c.i);sl.layers.push(cloneImg(t,p,{x:0,y:78,w:CW,h:269}))}
function stack(sl,t,a,b,c){sl.bg=bgFor(c.dir,c.pal,a,c.i);sl.layers.push(cloneImg(t,a,{x:18,y:18,w:304,h:185}));sl.layers.push(cloneImg(t,b,{x:18,y:222,w:304,h:185,z:11}))}
function contact(sl,t,set,c){sl.bg=bgFor(c.dir,c.pal,set[0],c.i);const gap=8,w=(CW-36-gap)/2,h=(CH-36-gap)/2;set.slice(0,4).forEach((p,k)=>sl.layers.push(cloneImg(t,p,{x:14+(k%2)*(w+gap),y:14+Math.floor(k/2)*(h+gap),w,h,z:10+k})))}
function applyLayout(k,sl,t,set,c){if(k==='full')full(sl,t,set[0],c);else if(k==='gallery')gallery(sl,t,set[0],c);else if(k==='offset')offset(sl,t,set[0],c);else if(k==='split')split(sl,t,set[0],set[1],c);else if(k==='duo')duo(sl,t,set[0],set[1],c);else if(k==='mosaic')mosaic(sl,t,set[0],set[1],set[2],c);else if(k==='colorFrame')colorFrame(sl,t,set[0],c);else if(k==='edge')edge(sl,t,set[0],c);else if(k==='wideBand')wideBand(sl,t,set[0],c);else if(k==='stack')stack(sl,t,set[0],set[1],c);else contact(sl,t,set,c)}
function spread(slides,start,span,t,p,c){for(let i=0;i<span;i++){const sl=slides[start+i];sl.bg=c.dir.bg==='light'?rgb(c.pal.light):rgb(c.pal.dark);sl.storySpan={photoId:p.id,start,span,seg:i};sl.frameLayout='spread';sl.layers.push(cloneImg(t,p,{x:-CW*i,y:0,w:CW*span,h:CH,storySpan:true,storySeg:i,storySpanCount:span}))}}
function desiredSlides(n,dir,span){if(n<=3)return n;const target=1.12+dir.density*1.35;return clamp(Math.ceil((n+(span-1))/target),4,10)}
function bestSpread(photos){return [...photos].map(p=>({p,s:slotScore(p,CW*2,CH,'spread')})).sort((a,b)=>b.s-a.s)[0]||null}
function makeCandidate(photos,t,dir,palette){let span=1,hero=null;const spreadPick=bestSpread(photos);if(spreadPick&&spreadPick.s>8&&photos.length>=6&&Math.random()<dir.spread){hero=spreadPick.p;span=2;if(photos.length>=9&&photoMeta(hero).aspect>1.5&&faceFit(hero,CW*3,CH)>.78&&Math.random()<dir.three)span=3}const count=desiredSlides(photos.length,dir,span),slides=Array.from({length:count},()=>({id:uid(),layers:[],bg:'#0b0b0d',palette:null,frameAuto:true})),occupied=new Set();if(span>1){const start=Math.min(Math.floor(Math.random()*Math.min(3,count-span+1)),count-span);spread(slides,start,span,t,hero,{dir,pal:palette,i:start});for(let i=0;i<span;i++)occupied.add(start+i)}
 let pool=shuffle(span>1?photos.filter(p=>p.id!==hero.id):photos),prevKind='';
 const usableIdx=[...Array(count).keys()].filter(i=>!occupied.has(i));
 for(let ui=0;ui<usableIdx.length;ui++){const si=usableIdx[ui],sl=slides[si],slotsLeft=usableIdx.length-ui;if(!pool.length)break;const desired=clamp(Math.ceil(pool.length/slotsLeft),1,4),kinds=[...new Set([...dir.layouts,desired>=4?'contact':null,desired>=3?'mosaic':null,desired>=2?'split':null,'full'].filter(Boolean))];const ranked=[];for(const k of kinds){const take=layoutTake(k);if(take>pool.length)continue;const a=assignFor(k,pool);if(!a)continue;let sc=a.fit-Math.abs(take-desired)*17+(k===prevKind?-16:0)+Math.random()*3;if(take>=3&&dir.density<.45)sc-=12;if(take===1&&dir.density>.7&&pool.length>slotsLeft)sc-=10;ranked.push({k,a,sc})}ranked.sort((a,b)=>b.sc-a.sc);const choice=pick(ranked.slice(0,Math.min(2,ranked.length)))||{k:'full',a:assignFor('full',pool)};const set=choice.a.set;pool=pool.filter(p=>!set.includes(p));sl.palette=ppal(set[0]);sl.frameLayout=choice.k;applyLayout(choice.k,sl,t,set,{dir,pal:palette,i:si});prevKind=choice.k}
 while(pool.length&&slides.length<10){const sl={id:uid(),layers:[],bg:'#0b0b0d',palette:null,frameAuto:true},desired=Math.min(2,pool.length),k=desired===2?'split':'gallery',a=assignFor(k,pool)||assignFor('full',pool),set=a.set;pool=pool.filter(p=>!set.includes(p));sl.frameLayout=k;sl.palette=ppal(set[0]);applyLayout(k,sl,t,set,{dir,pal:palette,i:slides.length});slides.push(sl)}
 slides.forEach(sl=>{sl.layers=sl.layers.filter(l=>l.type==='img'||(l.type==='text'&&l.userTouched))});return{slides,hero,span,dir:dir.name,palette}}
function candidateScore(c,photos,prev){let s=120;const layouts=c.slides.map(sl=>sl.frameLayout||'full');s+=new Set(layouts).size*4;for(let i=1;i<layouts.length;i++)if(layouts[i]===layouts[i-1])s-=12;const used=new Set(c.slides.flatMap(imgLayers).map(l=>l.photo?.id).filter(Boolean));s-=Math.max(0,photos.length-used.size)*100;const dense=c.slides.filter(sl=>imgLayers(sl).length>=3).length;if(dense>Math.ceil(c.slides.length*.4))s-=20;for(const sl of c.slides){if(!imgLayers(sl).length){s-=100;continue}for(const l of imgLayers(sl)){const m=photoMeta(l.photo),ff=faceFit(l.photo,l.w,l.h),area=l.w*l.h/AREA;if(m.faceCount){s+=(ff-.7)*35;if(ff<.72)s-=55;if(m.faceCount>=3&&area<.4)s-=60;if(m.faceCount===2&&area<.2)s-=25}if(area<.08)s-=12}}if(c.span>1)s+=10;if(prev){if(prev.dir===c.dir)s-=34;if((prev.layouts||[]).join('|')===layouts.join('|'))s-=50;if(prev.heroId&&prev.heroId===c.hero?.id)s-=8}return s+Math.random()*4}
function buildStory(){if(!S.photos?.length)return;const t=template();if(!t)return;const photos=[...S.photos],palette=setPalette(photos),dir=chooseDirection(),prev=S.frameLastDesign||null,candidates=[];for(let i=0;i<12;i++){const c=makeCandidate(photos,t,dir,palette);c.score=candidateScore(c,photos,prev);candidates.push(c)}candidates.sort((a,b)=>b.score-a.score);const chosen=pick(candidates.slice(0,Math.min(2,candidates.length)));S.slides=chosen.slides;S.framePalette=chosen.palette;S.frameArtDirection=chosen.dir;S.frameLastDesign={dir:chosen.dir,heroId:chosen.hero?.id||null,layouts:chosen.slides.map(sl=>sl.frameLayout||'full')};S.currentSlide=Math.min(S.currentSlide||0,S.slides.length-1);S.selected=null;S.selectedType=null;saveProject()}
window.FRAME_rebuildStory=()=>{try{if(typeof pushHistory==='function')pushHistory()}catch(e){}buildStory();renderAll();saveProject();toast('Nueva dirección ✦')};
const prevBuild=buildSlides;buildSlides=function(){prevBuild();buildStory()};
const style=document.createElement('style');style.textContent='#storyBadge,.storyBadge,.coverageBadge{display:none!important}';document.head.appendChild(style);
if(S.photos?.length){buildStory();renderAll()}
})();